//
// Autogenerated by Thrift Compiler (0.22.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;
var Int64 = require('node-int64');


var ttypes = module.exports = {};
var Message = module.exports.Message = function(args) {
  this.text = null;
  if (args) {
    if (args.text !== undefined && args.text !== null) {
      this.text = args.text;
    }
  }
};
Message.prototype = {};
Message.prototype[Symbol.for("read")] = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.text = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Message.prototype[Symbol.for("write")] = function(output) {
  output.writeStructBegin('Message');
  if (this.text !== null && this.text !== undefined) {
    output.writeFieldBegin('text', Thrift.Type.STRING, 1);
    output.writeString(this.text);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var File = module.exports.File = function(args) {
  this.fileName = null;
  this.fileSize = null;
  this.md5_hash = null;
  this.fileData = null;
  if (args) {
    if (args.fileName !== undefined && args.fileName !== null) {
      this.fileName = args.fileName;
    }
    if (args.fileSize !== undefined && args.fileSize !== null) {
      this.fileSize = args.fileSize;
    }
    if (args.md5_hash !== undefined && args.md5_hash !== null) {
      this.md5_hash = args.md5_hash;
    }
    if (args.fileData !== undefined && args.fileData !== null) {
      this.fileData = args.fileData;
    }
  }
};
File.prototype = {};
File.prototype[Symbol.for("read")] = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.fileName = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I64) {
        this.fileSize = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.md5_hash = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.fileData = input.readBinary();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

File.prototype[Symbol.for("write")] = function(output) {
  output.writeStructBegin('File');
  if (this.fileName !== null && this.fileName !== undefined) {
    output.writeFieldBegin('fileName', Thrift.Type.STRING, 1);
    output.writeString(this.fileName);
    output.writeFieldEnd();
  }
  if (this.fileSize !== null && this.fileSize !== undefined) {
    output.writeFieldBegin('fileSize', Thrift.Type.I64, 2);
    output.writeI64(this.fileSize);
    output.writeFieldEnd();
  }
  if (this.md5_hash !== null && this.md5_hash !== undefined) {
    output.writeFieldBegin('md5_hash', Thrift.Type.STRING, 3);
    output.writeString(this.md5_hash);
    output.writeFieldEnd();
  }
  if (this.fileData !== null && this.fileData !== undefined) {
    output.writeFieldBegin('fileData', Thrift.Type.STRING, 4);
    output.writeBinary(this.fileData);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

