//
// Autogenerated by Thrift Compiler (0.22.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;
var Int64 = require('node-int64');


var ttypes = module.exports = {};
var FilePayload = module.exports.FilePayload = function(args) {
  this.fileName = null;
  this.relativePath = null;
  this.fileSize = null;
  this.md5_hash = null;
  this.fileData = null;
  if (args) {
    if (args.fileName !== undefined && args.fileName !== null) {
      this.fileName = args.fileName;
    }
    if (args.relativePath !== undefined && args.relativePath !== null) {
      this.relativePath = args.relativePath;
    }
    if (args.fileSize !== undefined && args.fileSize !== null) {
      this.fileSize = args.fileSize;
    }
    if (args.md5_hash !== undefined && args.md5_hash !== null) {
      this.md5_hash = args.md5_hash;
    }
    if (args.fileData !== undefined && args.fileData !== null) {
      this.fileData = args.fileData;
    }
  }
};
FilePayload.prototype = {};
FilePayload.prototype[Symbol.for("read")] = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.fileName = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.relativePath = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I64) {
        this.fileSize = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.md5_hash = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRING) {
        this.fileData = input.readBinary();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

FilePayload.prototype[Symbol.for("write")] = function(output) {
  output.writeStructBegin('FilePayload');
  if (this.fileName !== null && this.fileName !== undefined) {
    output.writeFieldBegin('fileName', Thrift.Type.STRING, 1);
    output.writeString(this.fileName);
    output.writeFieldEnd();
  }
  if (this.relativePath !== null && this.relativePath !== undefined) {
    output.writeFieldBegin('relativePath', Thrift.Type.STRING, 2);
    output.writeString(this.relativePath);
    output.writeFieldEnd();
  }
  if (this.fileSize !== null && this.fileSize !== undefined) {
    output.writeFieldBegin('fileSize', Thrift.Type.I64, 3);
    output.writeI64(this.fileSize);
    output.writeFieldEnd();
  }
  if (this.md5_hash !== null && this.md5_hash !== undefined) {
    output.writeFieldBegin('md5_hash', Thrift.Type.STRING, 4);
    output.writeString(this.md5_hash);
    output.writeFieldEnd();
  }
  if (this.fileData !== null && this.fileData !== undefined) {
    output.writeFieldBegin('fileData', Thrift.Type.STRING, 5);
    output.writeBinary(this.fileData);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var TransferResult = module.exports.TransferResult = function(args) {
  this.success = null;
  this.message = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
    if (args.message !== undefined && args.message !== null) {
      this.message = args.message;
    }
  }
};
TransferResult.prototype = {};
TransferResult.prototype[Symbol.for("read")] = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.message = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TransferResult.prototype[Symbol.for("write")] = function(output) {
  output.writeStructBegin('TransferResult');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 1);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  if (this.message !== null && this.message !== undefined) {
    output.writeFieldBegin('message', Thrift.Type.STRING, 2);
    output.writeString(this.message);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

